name: test-caller-workflow

run-name: ${{ github.ref_name }} by @${{ github.actor }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
       - test*
       - dev
    
  workflow_dispatch:

jobs:
  climateiq-terraform-dev:
    uses: sahilchaudhry08/test-reusable-workflow/.github/workflows/reusable-test.yml@dev
    with:
      TF_VERSION: "1.0.0"
      APPROVAL_ENV: dev
      
