name: dev-caller-workflow

run-name: ${{ github.ref_name }} by @${{ github.actor }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} #dev
#   cancel-in-progress: true

on:
  push:
    branches-ignore:
           - dev
           - main
       
  pull_request:
            types: [closed]
            branches:
              - dev
    
  workflow_dispatch:

jobs:
  dev-workflow:
    uses: sahilchaudhry08/test-reusable-workflow/.github/workflows/reusable-test.yml@dev
    with:
      TF_VERSION: "1.0.0"
      APPROVAL_ENV: dev
